meson: add DEFS to CFLAGS
Adding a configuration flag as an include directory is wrong and errors
on BSDs.

ERROR: Include dir -DU_DISABLE_RENAMING=1 does not exist.

Matches the autotools build now.

Requires has_argument to fix non BSDs because of an annoying meson
quirk.

Signed-off-by: Rosen Penev <rosenp@gmail.com>