win32, msvc: fix missing linking against Bcrypt.lib
Fixes this link error:

dict.obj : error LNK2019: unresolved external symbol BCryptGenRandom referenced in function xmlInitRandom

Commit 2e9e758d1ecb52b73a43db79d326c18d7d94c8d7 (dict: Get random seed
from system PRNG, 2023-12-24) updated cmake, but not nmake, correct
this.